### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by OmgImAlexis** [watson/git-state#10]
Any chance you'd add promise support?

**Comment by watson** [comment]
Hi @OmgImAlexis 😃 Would you be ok with just using [util.promisify()](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original) from Node core?

**Comment by OmgImAlexis** [comment]
I was actually expecting promise support out of the box since people are now moving away from callbacks. I'm already using `promisify` for now but it'd be nicer if the library just supported Promises natively.

**Comment by watson** [comment]
I think the community is still split on this, though the Promise crowd is definitely getting bigger it seems 😅 Personally I'm not a big fan of promises unfortunately, so I'm pretty hesitant to add built-in support for it in my projects (that might change with async/await, but for now that's not yet widely supported in Node). I'm exited that you like my project enough to want to use it, but I hope you understand 😃
